# Generated by Django 4.2.2 on 2023-07-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='shashank', max_length=101),
            preserve_default=False,
        ),
    ]
