# Generated by Django 4.2.2 on 2023-07-16 13:19

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ticketApp', '0002_remove_ticket_location_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='problemSubtype',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='problemType', chained_model_field='problem_type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticketApp.problemsubtype'),
        ),
    ]
